# This is a basic workflow to help you get started with Actions

name: build-tags

# Controls when the workflow will run
on:
  # schedule:
  #     - cron: '0 0 */1 * *'
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'build tags'
        required: true
        type: string
      runner:
        description: 'Select runner type'
        required: false
        type: choice
        default: 'auto'
        options:
          - auto
          - self-hosted
          - github-hosted

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # test self runner - 快速探测是否可用
  probe-self-hosted:
    name:  Probe Self-hosted Runner
    # 只有在 auto 或 self-hosted 模式下才探测
    if: inputs.runner == 'auto' || inputs.runner == 'self-hosted'
    runs-on: self-hosted  
    timeout-minutes: 1  # 1分钟超时,快速检测 runner 是否空闲
    continue-on-error: true  # 允许此作业失败而不影响工作流
    steps:
      - name: Check Runner Availability
        run: |
          echo "Self-hosted runner is available and not busy."
          echo "Runner will handle this build task."

  # 优先在自托管服务器上构建
  build-self-hosted:
    name: Build on Self-hosted Runner
    needs: probe-self-hosted 
    # 在 self-hosted 模式下强制使用,或在 auto 模式下探针成功时使用
    if: |
      always() && 
      (inputs.runner == 'self-hosted' || 
       (inputs.runner == 'auto' && needs.probe-self-hosted.result == 'success'))
    runs-on: self-hosted  
    environment: token
    steps:
      - uses: actions/checkout@v3

      - name: Run build on self-hosted
        env: 
          DOCKER_NAME: gsdukbh
          LATEST: ${{inputs.tags}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MAIL: ${{ secrets.MAIL }}
          MY_NAME: ${{ secrets.MY_NAME}}
        run: |
          chmod +x build-tag.sh && ./build-tag.sh

  # 在 GitHub 服务器上构建 - 当自托管 runner 忙碌或离线时
  build-on-github:
    name: Build on GitHub-hosted Runner
    needs: probe-self-hosted
    # 在 github-hosted 模式下强制使用,或在 auto 模式下探针失败时使用
    if: |
      always() && 
      (inputs.runner == 'github-hosted' || 
       (inputs.runner == 'auto' && needs.probe-self-hosted.result != 'success'))
    runs-on: ubuntu-latest
    environment: token
    steps:
      - uses: actions/checkout@v3

      - name: Run build on GitHub-hosted
        env: 
          DOCKER_NAME: gsdukbh
          LATEST: ${{inputs.tags}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MAIL: ${{ secrets.MAIL }}
          MY_NAME: ${{ secrets.MY_NAME}}
        run: |
          echo "Self-hosted runner is busy or offline, using GitHub-hosted runner."
          chmod +x build-tag.sh && ./build-tag.sh 


          
